name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      keymap_path: config/nice60.keymap
      # ここでボードを具体的に指定します
      board: seeeduino_xiao_nrf52840 
